# Generated by Django 2.0.3 on 2018-03-16 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0003_voto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfil.Info'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
