# Generated by Django 2.0.3 on 2018-03-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0004_auto_20180316_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Perfil.Info'),
        ),
    ]
