# Generated by Django 2.0.3 on 2018-03-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0006_auto_20180316_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='acertos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='erros',
            field=models.IntegerField(default=0),
        ),
    ]
