# Generated by Django 2.0.3 on 2018-03-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0007_auto_20180317_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-points']},
        ),
    ]
